//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyplomWork.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerOption()
        {
            this.StudentAnswer = new HashSet<StudentAnswer>();
        }
    
        public int answerOptionId { get; set; }
        public string text { get; set; }
        public int isCorrectId { get; set; }
        public int questionId { get; set; }
    
        public virtual CorrectAnswer CorrectAnswer { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAnswer> StudentAnswer { get; set; }
    }
}
