//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyplomWork.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendanceId { get; set; }
        public int studentId { get; set; }
        public int lessonId { get; set; }
        public string is_present { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
