//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyplomWork.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReport
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Female { get; set; }
        public int TitleTestID { get; set; }
        public byte[] TestScreen { get; set; }
    
        public virtual TitleTest TitleTest { get; set; }
    }
}
