//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyplomWork.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int result_id { get; set; }
        public int student_id { get; set; }
        public int test_id { get; set; }
        public int score { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Users Users { get; set; }
    }
}
